### ISSUE TITLE
Email templates

### ISSUE THREAD

**Issue by mathlarocque** [plataformatec/mail_form#38]
Is there a way to have multiple template? Following your doc, I can create a template using a file in mail_form/contact.erb but apparently I can not create a second template... Is there an easy way to do so?

**Comment by carlosantoniodasilva** [comment]
It depends, why do you want a second template for? Are you sending different emails and want them to have different templates? It was not designed for that case, it only allows for a single template since it's a single notifier.

What you could do though is to [override the `deliver!` method](https://github.com/plataformatec/mail_form/blob/7cee02e12f46060c7ca60a38f4c015f8acb0a06c/lib/mail_form/delivery.rb#L150) which is responsible to actually trigger the notificar, and do something else.

Hope that helps.

**Comment by prwhitehead** [comment]
This is a little late, but I had the same problem and solved it by adding a header which was picked up by ActionMailer. 

https://github.com/plataformatec/mail_form/issues/48
